version: '3.9'

services:
  postgres-container:
    image: postgres:16.2
    container_name: cinema-postgres
#    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cinema_db
    networks:
      - cinema_network

networks:
  cinema_network:
    driver: bridge