springdoc:
  api-docs:
    path: "/api-docs"

server:
  port: 8085

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/cinema_db"
    username: "test"
    password: "test"
    driver-class-name: "org.postgresql.Driver"